 // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOe0siZYs3YzSJcbZIifq-SfBQStTOnk',
    appId: '1:433740758135:web:c2ca34d06696ffafdeda72',
    messagingSenderId: '433740758135',
    projectId: 'fire-sns-72e47',
    authDomain: 'fire-sns-72e47.firebaseapp.com',
    storageBucket: 'fire-sns-72e47.firebasestorage.app',
    measurementId: 'G-97RFK6YXMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsmRu9f9bvGxZcSyMJogSQ4-cga10seUg',
    appId: '1:433740758135:android:643be4b35f0b3fdddeda72',
    messagingSenderId: '433740758135',
    projectId: 'fire-sns-72e47',
    storageBucket: 'fire-sns-72e47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL8keHpp9OX9uWMiXsfa5UT8mTvyTBfVg',
    appId: '1:433740758135:ios:29b8446b9d86297fdeda72',
    messagingSenderId: '433740758135',
    projectId: 'fire-sns-72e47',
    storageBucket: 'fire-sns-72e47.firebasestorage.app',
    iosBundleId: 'com.example.fireSns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL8keHpp9OX9uWMiXsfa5UT8mTvyTBfVg',
    appId: '1:433740758135:ios:29b8446b9d86297fdeda72',
    messagingSenderId: '433740758135',
    projectId: 'fire-sns-72e47',
    storageBucket: 'fire-sns-72e47.firebasestorage.app',
    iosBundleId: 'com.example.fireSns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWOe0siZYs3YzSJcbZIifq-SfBQStTOnk',
    appId: '1:433740758135:web:c65d40c70426aa90deda72',
    messagingSenderId: '433740758135',
    projectId: 'fire-sns-72e47',
    authDomain: 'fire-sns-72e47.firebaseapp.com',
    storageBucket: 'fire-sns-72e47.firebasestorage.app',
    measurementId: 'G-NRJJMY74HB',
  );

}